export type AlexaCapabilityInterface =
    "Alexa.BrightnessController" |
    "Alexa.Business.Reservation.Room" |
    "Alexa.Calender" |
    "Alexa.CameraStreamController" |
    "Alexa.ChannelController" |
    "Alexa.ColorController" |
    "Alexa.ColorTemperatureController" |
    "Alexa.ContactSensor" |
    "Alexa.Cooking" |
    "Alexa.FoodTemperatureController" |
    "Alexa.FoodTemperatureSensor" |
    "Alexa.Cooking.PresetController" |
    "Alexa.Cooking.TemperatureController" |
    "Alexa.Cooking.TemperatureSensor" |
    "Alexa.Cooking.TimeController" |
    "Alexa.CustomIntent" |
    "Alexa.Discovery" |
    "Alexa.DoorbellEventSource" |
    "Alexa.EndpointHealth" |
    "Alexa.EqualizerController" |
    "Alexa.EventDetectionSensor" |
    "Alexa.InputController" |
    "Alexa.InventoryLevelSensor" |
    "Alexa.KeypadController" |
    "Alexa.Launcher" |
    "Alexa.LockController" |
    "Alexa.MediaMetadata" |
    "Alexa.MeetingClientController" |
    "Alexa.ModeController" |
    "Alexa.MotionSensor" |
    "Alexa.Networking.AccessController" |
    "Alexa.Networking.ConnectedDevice" |
    "Alexa.Networking.HomeNetworkController" |
    "Alexa.PercentageController" |
    "Alexa.PlaybackController" |
    "Alexa.PlaybackStateReporter" |
    "Alexa.PowerController" |
    "Alexa.PowerLevelController" |
    "Alexa.RangeController" |
    "Alexa.RecordController" |
    "Alexa.RemoteVideoPlayer" |
    "Alexa.RTCSessionController" |
    "Alexa.SceneController" |
    "Alexa.SecurityPanelController" |
    "Alexa.SeekController" |
    "Alexa.Speaker" |
    "Alexa.StepSpeaker" |
    "Alexa.TemperatureSensor" |
    "Alexa.ThermostatController" |
    "Alexa.TimeHoldController" |
    "Alexa.ToggleController" |
    "Alexa.VideoController" |
    "Alexa.WakeOnLANController"
