@startuml
skinparam monochrome true
skinparam padding 4

actor "User" as user
participant "Alexa\lDevice" as echo
participant "Alexa\lService" as alexa_service
participant "Skill\lLambda" as lambda
participant "IoT\lCore" as iot
participant "Node\lRED" as node_red
participant "Irdroid" as irdroid

== Initialization of Communication ==
node_red -> iot: connect
note left
    Raspberry Pi located in home network
    starts the communication into the cloud
    using MQTT protocol secured by certificates
end note
iot -> node_red
node_red -> iot: subscribe to topic:\l//mysmarthome/request/+//
iot -> node_red

== Control of Device via Voice ==
user -> echo: Alexa, turn on cooking hood
echo -> alexa_service
alexa_service -> lambda: //TurnOn//\ldirective of\l//Alexa.PowerController//\lInterface

group if //Skill Lambda// is cold
lambda -> iot: connect
note right
    Connection to IoT Core
    using //aws-iot-device-sdk//
    with //WSS// protocol
    secured by //IAM//
end note
iot -> lambda
lambda -> iot: subscribe to response topics\l//mysmarthome/response/+//
iot -> lambda
end
lambda -> iot: publish on request topic\l//mysmarthome/request/<uuid>//:\l//TurnOn// directive
note right
    Each request generates
    a random <uuid>.
end note
iot -> node_red: send //TurnOn// directive
node_red -> irdroid: send //KEY_POWER//
node_red -> iot: publish on response topic\l//mysmarthome/response/<uuid>//:\l//TurnOn// response event
iot -> lambda: send response message
lambda -> alexa_service: //Response// event
alexa_service -> echo
echo -> user: confirmation\lbeep
@enduml